"""add_device_os

Revision ID: 35083de9af22
Revises: 31f95b5d53de
Create Date: 2026-06-18 14:41:18.423691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35083de9af22'
down_revision: Union[str, Sequence[str], None] = '31f95b5d53de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os', sa.String(length=50), nullable=True))

    with op.batch_alter_table('pack_version_rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_alerted_rules_rule_pack'), type_='unique')
        batch_op.create_unique_constraint('uq_pack_version_rules_rule_pack', ['rule_id', 'rule_type', 'pack_version_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pack_version_rules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pack_version_rules_rule_pack', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_alerted_rules_rule_pack'), ['rule_id', 'rule_type', 'pack_version_id'])

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('os')

    # ### end Alembic commands ###
